{% set name = "libdate" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/HowardHinnant/date/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7a390f200f0ccd207e8cff6757e04817c1a0aec3e327b006b7eb451c57ee3538

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake }}
    - ninja {{ ninja }}
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                    # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}              # [x86_64 and c_compiler_version == "7.2.*"]
  host:
    # Use pins to control cos6/cos7 match
    - libgcc-ng  {{ libgcc }}                    # [x86_64 and c_compiler_version == "7.2.*"]
    - libstdcxx-ng  {{ libstdcxx }}              # [x86_64 and c_compiler_version == "7.2.*"]

test:
  commands:
    - test -f $PREFIX/include/date/date.h

about:
  home: https://github.com/HowardHinnant/date
  summary: A date and time library based on the C++11/14/17 <chrono> header
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
